name: htd
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.7
  geolocator: ^5.3.2+2
  firebase_storage: ^3.1.6
  firebase_auth: ^0.16.1
  backdrop: ^0.4.1
  file_picker: ^1.13.3
  google_sign_in: ^4.5.1
  firebase_image: ^0.1.6
  firebase_analytics: ^5.0.16
  image_picker: ^0.6.7+4
  google_maps_flutter: ^1.0.6
  url_launcher: ^5.5.0
  cached_network_image: ^2.3.1
  convex_bottom_bar: ^2.4.1
  latlong: ^0.6.1
  gpx: ^1.1.1
  flutter_phoenix: ^0.1.0
  shared_preferences: ^0.5.10
  google_fonts: ^1.1.0
  flutter_map_marker_cluster: ^0.3.1
  firebase_database: ^3.1.6
  image_downloader: ^0.20.0
  table_calendar: ^2.3.0
  internet_speed_test: ^1.1.2+1
  connectivity: ^2.0.1
  wifi: ^0.1.5
  flutter_inappwebview: ^4.0.0+4
  flutter_webview_plugin: ^0.3.11
  firebase_messaging: ^6.0.9
  flutter_local_notifications: ^3.0.1+6
  get_it: ^5.0.1
  http: ^0.12.2
  flutter_chess_board: ^0.9.4
  dotted_border: ^1.0.7
  google_maps_cluster_manager: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/map_style.txt
    - assets/images/
  uses-material-design: true